sudo: false

language: java
jdk:
  - oraclejdk8
env:
  global:
    - secure: "lEASIgCN+AHGLPnbya4rrKNjbHlcJFvY9u9S+ghzJXMyv/yF6oVgU+QcAyffm36RqX6VgEnZQ7hhWBZgqSaeX7Tt7T0BWfQZb+69BiMdzuTU+4fbyyuP1JRtx62NSEEHlsdORHrT2K8s66Lbj9hn1oG/5ABaObEqt3znhz4l9yZ2UwS20mGDJjBwN4sJLZe37GD/MSJTe1sDDNSIwk+wVlf6leEj17DNItUBnnIqy47BGLnFP0JvDXT2B58eV9a8nxcGgQKxiqEH9hBEaTyt42J8vV+T6hvEwVcWU9PFbdWpXwuXzFeh4DuSDGwAQJwPimq6Xx0DZQRsgoLwPhtCLvvqO5qTMI8Csf4lS2pIyCBzAlqAhm83G7WPYS8yjT+wjlp4f6m3xifB8125K1Q66yIfkIbCAmcSUIvTV0Fgxm9O5VeFKLJwhDaA+4zdq8Vgrw5iQYoyOz6PreENK+H0ojGXCgieTEgmsNW9aNANHpDZ+GrEri1eS9D7MshBq0C44xaILAGmQfNbzdc1wUo3rTibCYd21ffWYdKRKp3Xd15em8ms6yUdTVhaUooXP/aBs6CR9rlpr5KfYQm8Izs+66RRha5ICgrJdRRUBFZfBStciIwQsFNBWhpMyRHEULOgGsTfQhf1DHv2VZxgKAnwPDn1goF54an8bx9EVkVUFl8="
cache:
  directories:
    - $HOME/.m2
  
script: 
  - "mvn cobertura:cobertura"
  - "mvn javadoc:javadoc"

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - bash Deploy_JavaDoc.sh

notification:
  email:
    on_success: never
    on_failure: always
